### ISSUE TITLE
OSError: Unable to open SeqRepo directory /usr/local/share/seqrepo/latest when using seqrepo

### ISSUE THREAD

**Issue by algarsi3** [ga4gh/vrs-python#61]
I followed the instructions to install and configure vrs-python.
```bash
$ docker ps
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS          PORTS     NAMES
ba533a28fd60   biocommons/uta:uta_20180821              "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes             stack_uta_1
888be6a91e11   biocommons/seqrepo-rest-service:latest   "seqrepo-rest-service"   18 minutes ago   Up 18 minutes             stack_seqrepo-rest-service_1
```

However, when I try to execute jupyter examples I get the following error:
```python
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5000/seqrepo/1/sequence/NC_000019.10?start=44908821&end=44908822
```

I saw that there are two examples to test the containers in the docker-compose.yml file, while this works as expected:
```bash
$ psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from transcript'
249909
```

This returns e the same error described above:
```bash
$ curl -f http://0.0.0.0:5000/seqrepo/1/sequence/NP_001274413.1
curl: (22) The requested URL returned error: 500 INTERNAL SERVER ERROR
```

I can access to the `http://localhost:5000/seqrepo/1/ui/` URL, but even when I try `/ping` I get the 500 error. Any ideas on how could I solver this?

**Comment by reece** [comment]
Confirmed problem. I'll need some more time to investigate the cause.

**Comment by korikuzma** [comment]
Reopening because our lab is still getting this error. I had to change the docker-compose.yaml (removing `network_mode: host` and adding `ports`) as shown below:

```
version: "3"

services:
  seqrepo-rest-service:
    ports:
      - 5000:5000
    # Test: curl http://localhost:5000/seqrepo/1/sequence/refseq:NM_000551.3
    image: biocommons/seqrepo-rest-service:latest
    volumes:
      - seqrepo_vol:/usr/local/share/seqrepo

  uta:
    ports:
      - 5432:5432
    # Test:
    # psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from transcript'
    # 249909
    image: biocommons/uta:uta_20180821
    volumes:
      - uta_vol:/var/lib/postgresql/data

volumes:
  seqrepo_vol:
    external: true
  uta_vol:
    external: true
```

@reece I know it's been a long time since you looked at this, but you be able to assist with this again?
